const mongoose = require('mongoose')

const propostaScheema = mongoose.Schema({
    dataImportacao: String,
    vigencia: String,
    proposta: String,
    statusMotor: String,
    status: String,
    status1Analise: String,
    status2Analise: String,
    status3Analise: String,
    produto: String,
    produtor: String,
    uf: String,
    administradora: String,
    codCorretor: String,
    entidade: String,
    tipoVinculo: String,
    nome: String,
    idade: String,
    numeroVidas: String,
    valorMedico: String,
    valorDental: String,
    valorTotal: String,
    primeiraDevolucao1: String,
    primeiraDevolucao2: String,
    primeiraDevolucao3: String,
    primeiraDevolucao4: String,
    reprotoclo1: String,
    reprotoclo2: String,
    reprotoclo3: String,
    segundoReprotocolo1: String,
    segundoReprotocolo2: String,
    segundoReprotocolo3: String,
    observacoesDevolucao: String,
    analista: String,
    dataConclusao: String,
    ligacao: String,
    prc: String,
    motivoCancelamento: String,
    evidenciaFraude: String,
    cpfCorretor: String,
    nomeCorretor: String,
    telefoneCorretor: String,
    nomeSupervisor: String,
    cpfSupervisor: String,
    telefoneSupervisor: String,
    cpf: String,
    planoAmil: String,
    dataInicioPlanoAmil: String,
    dataFimPlanoAmil: String,
    custoPlanoAmil: String,
    documentoIdentificacao: String,
    declaracaoAssociado: String,
    vinculadosSimNao: String,
    vinculados: String,
    planoAnterior: String,
    sisAmilDeacordo: String,
    faltaDoc: String,
    site: String,
    contrato: String,
    analistaPreProcessamento: String,
    dataConclusaoPre: String,
    observacoes: String,
    categoriaCancelamento: String,
    erroSistema: String

}, {
    timestamps: true
})

module.exports = mongoose.model('PropostasElegibilidade', propostaScheema)