const mongoose = require('mongoose')

const UrgenciaEmergenciaScheema = mongoose.Schema({
    mes: String,
    data: String,
    numAssociado: String,
    nomeAssociado: String,
    dataNascimento: String,
    idade: String,
    dataAdesao: String,
    dataInclusao: String,
    dataExclusao: String,
    nomePlano: String,
    tipoContrato: String,
    ddd: String,
    telefone: String,
    email: String,
    prc: String,
    indResp1: String,
    indResp2: String,
    indResp3: String,
    indResp4: String,
    indResp5: String,
    indResp6: String,
    indResp7: String,
    indResp8: String,
    indResp9: String,
    proposta: String,
    pedido: String,
    dataSolicitacao: String,
    idadeSolic: String,
    dataAutorizacao: String,
    indCarater: String,
    nomePrestador: String,
    cid: String,
    cidPrin: String,
    nomeCidPrin: String,
    cidSec: String,
    nomeCidSec: String,
    sitAutoriz: String,
    nomeTratamento: String,
    relatorioMedico: String,
    cpt: String,
    contato1: String,
    contato2: String,
    contato3: String,
    observacoes: String,
    descricaoCid: String,
    obsUnder: String,
    retorno: String,
    status: String,
    analista: String,
    dataRecebimento: String,
    dataConclusao: String,
    responsavel: String,
    faturado: String,
    dataFaturamento: String,
    nf: String,
}, {
    timestamps: true
})

module.exports = mongoose.model('UrgenciasEmergencia', UrgenciaEmergenciaScheema)

