const mongoose = require('mongoose')

const dadosEntrevistaScheema = mongoose.Schema({
    nome: String,
    cpf: String,
    dataNascimento: Date,
    dataEntrevista: Date,
    proposta: String,
    tipoFormulario: String,
    profissao: String,
    carteiraVacina: String,
    maFormacao: String,
    tratamento: String,
    espectro: String,
    deficitAtencao: String,
    preenchimentoDps: String,
    responsavel: String,
    patologias: String,
    altura: String,
    peso: String,
    imc: String,
    problemaCoracao: String,
    diabetes: String,
    cisto: String,
    problemaNeurologico: String,
    dorCostas: String,
    aparelhoOrtodontico: String,
    hiv: String,
    disturbio: String,
    problemaRespiratorio: String,
    problemaRenal: String,
    perguntaMasculino: String,
    perguntaFeminina: String,
    gravidez: String,
    procuraMedica: String,
    hospitalizacao: String,
    doencaEndemica: String,
    atividadeArriscada: String,
    realizarProcedimento: String,
    planoSaude: String,
    alimentacao: String,
    horasNoite: String,
    movimentacao: String,
    usoMedicamentos: String,
    cigarro: String,
    substanciasIlicitas: String,
    bebida: String,
    doencaHereditaria: String
})

module.exports = mongoose.model('DadosEntrevista', dadosEntrevistaScheema)