const express = require('express')
const router = express.Router()
const elegibilidadeController = require('../../controllers/elegibilidadeController')
const auth = require('../../middlewares/auth')

//Rotas Elegibilidade

router.get('/show', auth, elegibilidadeController.show)
router.post('/upload', auth, elegibilidadeController.upload)
router.get('/propostas/analiseDoc', auth, elegibilidadeController.mostrarAnaliseDoc)
router.put('/atribuir/preProcessamento', auth, elegibilidadeController.atribuirAnalistaPre)
router.get('/infoProposta/:id', auth, elegibilidadeController.mostrarInfoPropostaId)
router.get('/propostas/:status/:analista', auth, elegibilidadeController.propostasAnalistaPorStatus)
router.get('/proposta/filtro', auth, elegibilidadeController.filtro)
router.get('/entidades/:status', auth, elegibilidadeController.entidades)
router.put('/atribuir/analise', auth, elegibilidadeController.atribuirAnalista)
router.get('/propostas/:status/proposta/:proposta', auth, elegibilidadeController.filtroProposta)
router.put('/proposta/alterarStatus', auth, elegibilidadeController.statusEmAndamento)
router.put('/proposta/fase1', auth, elegibilidadeController.fase1)
router.put('/proposta/fase2', auth, elegibilidadeController.fase2)
router.post('/agenda/comentario', auth, elegibilidadeController.comentario)
router.get('/agenda/:id', auth, elegibilidadeController.buscarAgenda)
router.get('/prc', auth, elegibilidadeController.buscarPrc)
router.put('/enviarUnder', auth, elegibilidadeController.enviarUnder)
router.put('/enviarFaseCancelamento', auth, elegibilidadeController.enviarFaseCancelamento)
router.put('/devolver', auth, elegibilidadeController.devolver)
router.put('/cancelar', auth, elegibilidadeController.cancelar)
router.post('/cancelarCpf', auth, elegibilidadeController.cancelarCpf)
router.get('/consultaCpf/:cpf', auth, elegibilidadeController.consultaCpfCancelado)
router.get('/producao/:data', auth, elegibilidadeController.producaoDiaria)
router.get('/report', auth, elegibilidadeController.report)
router.get('/corretor/:corretor', auth, elegibilidadeController.propostasCorretor)
router.get('/blacklist', auth, elegibilidadeController.blacklist)
router.post('/registrar/proposta', auth, elegibilidadeController.registroPropostaManual)
router.get('/show/propostasManual', auth, elegibilidadeController.showPropostasManual)
router.get('/show/propostaManual/andamento', auth, elegibilidadeController.showPropostasManualAndamento)
router.put('/salvarDiploma', auth, elegibilidadeController.salvarDiploma)
router.post('/buscarDiploma', auth, elegibilidadeController.buscarDiploma)
router.get('/universidades', auth, elegibilidadeController.buscarUniversidades)
router.get('/cursos', auth, elegibilidadeController.buscarCursos)
router.put('/atualizarObservacoes', auth, elegibilidadeController.atualizarObservacoes)
router.put('/concluirPropostaManual', auth, elegibilidadeController.concluirPropostaManual)
router.post('/uploadDivergencias', auth, elegibilidadeController.divergencias)
router.get('/planosBlacklist', auth, elegibilidadeController.planosBlacklist)
router.get('/relatorioProducao', elegibilidadeController.relatorioProducao)
router.put('/semDocumentos', auth, elegibilidadeController.semDocumentos)
router.get('/semDocumentos', auth, elegibilidadeController.getSemDocumentos)
router.put('/documentoRecebido', auth, elegibilidadeController.documentoRecebido)
router.post('/planosBlacklist', auth, elegibilidadeController.adicionarPlanoBlacklist)
router.delete('/planosBlacklist/:id', auth, elegibilidadeController.removerPlanoBlacklist)
router.get('/producaoMensal/:mes/:analista', auth, elegibilidadeController.produtividadeMensal)
router.put('/voltarProposta', auth, elegibilidadeController.voltarProposta)
router.get('/relatorioProducaoMensal/:mes', auth, elegibilidadeController.relatorioProducaoMensal)
router.get('/analitico/:mes', auth, elegibilidadeController.analiticoMensal)
router.get('/producaoIndividualElegi/:mes', auth, elegibilidadeController.producaoIndividualElegi)


module.exports = router