const express = require('express')
const router = express.Router()
const rsdController = require('../../controllers/rsdController')
const auth = require('../../middlewares/auth')

//RSD

router.post('/upload', auth, rsdController.upload)
router.post('/uploadQuarentena', auth, rsdController.uploadQuarentena)
router.post('/subir', auth, rsdController.subir)
router.get('/pedidos/todos', auth, rsdController.show)
router.get('/pessoas/:mo', auth, rsdController.mostrarPessoa)
router.put('/pessoas/editar', auth, rsdController.atualizarInformacoes)
router.get('/pedido/:pedido', auth, rsdController.buscarPedido)
router.put('/clinica/busca', auth, rsdController.buscarClinica)
router.put('/pedido/editar', auth, rsdController.editarPedido)
router.post('/pedido/criar', auth, rsdController.criarPedido)
router.get('/mo/:protocolo', auth, rsdController.buscarMoProtocolo)
router.post('/protocolo/criar', auth, rsdController.criarProtocolo)
router.post('/pacote/criar', auth, rsdController.criarPacote)
router.get('/pedidos/mo/:mo', auth, rsdController.buscarPedidosMo)
router.put('/pacote/assumir', auth, rsdController.assumirPacote)
router.get('/pedidos/pacote/:pacote', auth, rsdController.buscarPedidosPacote)
router.post('/gravacao/anexar/:pacote', auth, rsdController.anexarGravacao)
router.get('/arquivos/:pacote', auth, rsdController.buscarArquivos)
router.get('/formasPagamento', auth, rsdController.buscarFormasPagamento)
router.get('/statusFinalizacoes', auth, rsdController.buscarStatusFinalizacao)
router.put('/pedido/atualizar', auth, rsdController.atualizarPedido)
router.get('/agenda/:pacote', auth, rsdController.buscarAgenda)
router.get('/pedidos/naoFinalizados/naoFinalizados', auth, rsdController.buscarPedidosNaoFinalizados)
router.get('/pedidos/naoFinalizados/filtro', auth, rsdController.filtroPedidosNaoFinalizados)
router.get('/operadoras', auth, rsdController.buscarOperadoras)
router.post('/pedido/criar/individual', auth, rsdController.criarPedidoIndividual)
router.post('/operadoras/criar', auth, rsdController.criarOperadora)
router.put('/operadoras/editar', auth, rsdController.editarOperadora)
router.get('/operadora/:id', auth, rsdController.buscarOperadora)
router.get('/concluidos/:pesquisa', auth, rsdController.buscarPedidosFinalizados)
router.put('/pedido/devolverAmil', auth, rsdController.devolverAmil)
router.post('/agenda/novoParecer', auth, rsdController.escrevarAgenda)
router.put('/pacote/voltarFase', auth, rsdController.voltarFase) //parei aqui na doc
router.put('/pedido/voltarFase', auth, rsdController.voltarFasePedido)
router.put('/pedido/prioridadeDossie', auth, rsdController.adicionarPrioridadeDossie)
router.put('/pacote/prioridadeDossie', auth, rsdController.prioridadeDossiePacote)
router.put('/pacote/devolver', auth, rsdController.devolverPacote)
router.put('/protocolo/devolver', auth, rsdController.devolverProtocolo)
router.get('/relatorio/:aPartir/:ate', auth, rsdController.relatorioAmil)
router.get('/download/:idPacote/:filename', rsdController.download)
router.get('/producaoDiaria/:data', auth, rsdController.producaoDiaria)
router.post('/baixaAgd', auth, rsdController.baixaAgd)
router.get('/teste', rsdController.teste)
router.get('/relatorioProducao', rsdController.relatorioProducao)
router.get('/producaoMensal/:mes/:analista', auth, rsdController.producaoMensal)
router.post('/formaPagamento', auth, rsdController.adicionarFormaPagamento)
router.delete('/formaPagamento/:id', auth, rsdController.deleteFormaPagamento)
router.post('/finalizacao', auth, rsdController.adicionarStatusFinalizacao)
router.delete('/finalizacao/:id', auth, rsdController.deleteStatusFinalizacao)
router.get('/relatorioProducaoMensal/:mes', auth, rsdController.relatorioProducaoMensal)
router.get('/producaoIndividualRsd/:mes', auth, rsdController.producaoIndividualRsd)
router.get('/quantidadeProducaoRsd/:mes', auth, rsdController.quantidadeProducaoRsd)
router.get('/quantidadePagamentosRsd/:mes', auth, rsdController.quantidadePagamentosRsd)
router.get('/quantidadeStatusGerenciais/:mes', auth, rsdController.quantidadeStatusGerenciais)
router.get('/quantidadeStatusAmil/:mes', auth, rsdController.quantidadeStatusAmil)
router.get('/quantidadePedidosIndeferidos/:mes', auth, rsdController.quantidadePedidosIndeferidos)
router.get('/analitico/:mes', auth, rsdController.analiticoMensal)
router.get('/producaoIndividual/:mes/:analista', auth, rsdController.producaoIndividual)
router.get('/comparativoProducao/:mes/:analista', auth, rsdController.comparativoProducao)

module.exports = router