const express = require('express')
const router = express.Router()
const sindicanciaController = require('../../controllers/sindicanciaController')
const auth = require('../../middlewares/auth')

router.get('/demanda', auth, sindicanciaController.getDemandas)
router.get('/areaEmpresa', auth, sindicanciaController.getAreaEmpresa)
router.get('/tipoServico', auth, sindicanciaController.getTipoServico)
router.get('/status', auth, sindicanciaController.getStatus)
router.get('/analistasExecucao', auth, sindicanciaController.getAnalistasExecucao)
router.post('/demanda/beneficiario', auth, sindicanciaController.createBeneficiario)
router.post('/demanda/prestador', auth, sindicanciaController.createPrestador)
router.post('/demanda/beneficiario/delete', auth, sindicanciaController.deleteBeneficiario)
router.post('/demanda/prestador/delete', auth, sindicanciaController.deletePrestador)
router.get('/demanda/beneficiario/:id', auth, sindicanciaController.getBeneficiarios)
router.get('/demanda/prestador/:id', auth, sindicanciaController.getPrestadores)
router.post('/demanda/relatorio', auth, sindicanciaController.relatorioDemanda)
router.post('/demanda/tipoIrregularidade', auth, sindicanciaController.createTipoIrregularidade)
router.get('/demanda/tipoIrregularidade', auth, sindicanciaController.getTipoIrregularidade)
router.delete('/demanda/tipoIrregularidade/:id', auth, sindicanciaController.deleteTipoIrregularidade)
router.post('/demanda/irregularidade', auth, sindicanciaController.createIrregularidade)
router.get('/demanda/irregularidade/:id', auth, sindicanciaController.getIrregularidade)
router.delete('/demanda/irregularidade/:id', auth, sindicanciaController.deleteIrregularidade)
router.post('/demanda/agenda', auth, sindicanciaController.createAgenda)
router.get('/demanda/agenda/:id', auth, sindicanciaController.getAgenda)
router.delete('/demanda/agenda/:id', auth, sindicanciaController.deleteAgenda)
router.post('/demanda/valor', auth, sindicanciaController.createValor)
router.get('/demanda/valor/:id', auth, sindicanciaController.getValor)
router.delete('/demanda/valor/:id', auth, sindicanciaController.deleteValor)
router.post('/demanda/finalizar', auth, sindicanciaController.finalizarDemanda)
router.get('/demanda/quantidadeDemandasResponsaveis/:mes', auth, sindicanciaController.quantidadeDemandasResponsaveis)
router.get('/demanda/quantidadeIndividualSindicancia/:mes', auth, sindicanciaController.quantidadeIndividualSindicancia)
router.post('/demanda/complementacao', auth, sindicanciaController.createComplementacao)

module.exports = router