const express = require('express')
const router = express.Router()
const teleEntrevistaController = require('../../controllers/teleEntrevistaController')
const horarioController = require('../../controllers/horarioController')
const auth = require('../../middlewares/auth')

//Tele Entrevistas

router.post('/gerarHorarios', auth, horarioController.gerar)
router.get('/buscarDiasDisponiveis/:enfermeiro', auth, horarioController.search)
router.get('/buscarHorariosDisponiveis/:enfermeiro/:data', auth, horarioController.searchHorarios)
router.get('/buscarHorariosNaoDisponiveis/:responsavel/:data', auth, horarioController.buscarHorariosNaoDisponiveis)
router.put('/agendar', auth, horarioController.agendar)
router.put('/fecharDia', auth, horarioController.fecharDia)
router.put('/fecharHorarios', auth, horarioController.fecharHorarios)
router.put('/reabrirHorarios', auth, horarioController.reabrirHorarios)
router.get('/horarios/disponiveis', auth, horarioController.buscarHorarioDisponiveis)
router.get('/perguntas', auth, teleEntrevistaController.mostrarPerguntas)
router.post('/formulario', auth, teleEntrevistaController.enviarDadosFormulario)
router.get('/cids/pesquisa/:pesquisa', auth, teleEntrevistaController.buscarCids)
router.get('/dadosEntrevista/:proposta/:nome', auth, teleEntrevistaController.mostrarDadosEntrevista)
router.get('/dadosEntrevista', auth, teleEntrevistaController.mostrarDadosEntrevistas)
router.get('/buscar/dadosEntrevista/:id', auth, teleEntrevistaController.mostrarDadosEntrevistaId)
router.put('/editar/dadosEntrevista', auth, teleEntrevistaController.salvarDadosEditados)
router.get('/propostas/anexar', auth, teleEntrevistaController.buscarPropostasNaoAnexadas)
router.put('/propostas/anexar', auth, teleEntrevistaController.anexarSisAmil)
router.put('/reagendar', auth, teleEntrevistaController.reagendar)
router.put('/cancelar', auth, teleEntrevistaController.cancelarProposta)
router.get('/naoFaturadas', auth, teleEntrevistaController.buscarNaoFaturados)
router.put('/faturar', auth, teleEntrevistaController.realizarFaturamento)
router.get('/faturamento/filtros/:status/:data', auth, teleEntrevistaController.filtrosFaturamento)
router.get('/report/agendadas', auth, teleEntrevistaController.reportAgendadas)
router.put('/propostas/vigencia/update', auth, teleEntrevistaController.atualizarVigencia)
router.get('/producao/diaria/:data', auth, teleEntrevistaController.producaoDiaria)
router.post('/cid/adicionar', auth, teleEntrevistaController.adicionarCid)
router.get('/mensagens/:data', teleEntrevistaController.gerarMensagens)
router.post('/horario/novo', auth, horarioController.abrirNovoHorario)
router.put('/dadosEntrevista/dataNascimento', auth, teleEntrevistaController.alterarDataNascimento)
router.get('/realizadas/:pesquisa', auth, teleEntrevistaController.buscarEntrevistaRealizada)
router.put('/realizadas/alterarSexo', auth, teleEntrevistaController.alterarSexoEntrevistaRealizada)
router.put('/mandarImplatacao', auth, teleEntrevistaController.mandarImplantacao)
router.put('/implantar', auth, teleEntrevistaController.implantar)
router.get('/naoImplantadas', auth, teleEntrevistaController.naoImplantadas)
router.put('/voltar', auth, teleEntrevistaController.voltarEntrevista)
router.get('/qualidade', auth, teleEntrevistaController.entrevistasQualidade)
router.get('/diasDisponiveis', auth, horarioController.diasDisponiveis)
router.get('/horariosDisponiveis/:data', horarioController.buscarHorariosDisponiveis)
router.get('/analistasDisponiveis/:data/:horario', auth, horarioController.buscarAnalistasDisponiveis)
router.put('/reenviarHorariosDisponiveis', auth, teleEntrevistaController.reenviarHorariosDisponiveis)
router.get('/teste/producaoTele', teleEntrevistaController.mostrarDadosProducaoTele)
router.get('/teste/producaoRns', teleEntrevistaController.mostrarDadosProducaoRns)
router.get('/relatorioProducao', teleEntrevistaController.relatorioProducao)
router.get('/rendimentoIndividualMensal/:mes/:analista', auth, teleEntrevistaController.rendimentoIndividualMensal)
router.get('/producaoMensal/:mes', auth, teleEntrevistaController.ProducaoMensal)
router.get('/reportAnexos/:data', auth, teleEntrevistaController.reportAnexos)
router.get('/entrevistasEntreDatas', auth, teleEntrevistaController.buscarEntrevistasEntreDatas)
router.get('/producao/anexos/:analista/:mes', auth, teleEntrevistaController.producaoMensalAnexos)
router.get('/verificarHorarioReaberto', auth, horarioController.verificarReaberto)
router.post('/uploadImplantacao', auth, teleEntrevistaController.uploadImplantacao)
router.get('/verificarAgendamento/:data/:horario/:enfermeiro', auth, horarioController.verificarAgendamento)
router.get('/relatorioPropostasMes/:mes', auth, teleEntrevistaController.relatorioProdutividadeMes)
router.get('/relatorioRnUePorMes/:mes', auth, teleEntrevistaController.relatorioProdutivdadeMensalRnUe)
router.get('/agendasFechadas', auth, horarioController.getAgendasFechadas)
router.get('/relatorioProdutividadeAnexosMensal/:mes', auth, teleEntrevistaController.relatorioProdutividadeAnexosMensal)
router.post('/criarHorarios', horarioController.gerarHorarioIndividual)
router.get('/quantidadeAnalistasPorMes/:mes', auth, teleEntrevistaController.quantidadeAnalistasPorMes)
router.post('/filterEntrevistasRealizdas', auth, teleEntrevistaController.filterEntrevistasRealizadas)
router.post('/filterQueryDadosEntrevistas', auth, teleEntrevistaController.filterQueryDadosEntrevistas)
router.get('/filterProducao', auth, teleEntrevistaController.filterProducao)

module.exports = router